shop/urls.py
from django.urls import path
from shop.views import *

app_name = 'shop'
urlpatterns = [
    path('',index),
    path('sign_up/',sign_up, name='sign_up'),
    path('login/',login, name='login'),
    path('logout/',exit, name='logout'),
    path('index/',index, name='index'),
    path('shop_register/', shop_register, name='shop_register'),
    path('shop_update/', shop_update, name='shop_update'),
    path('shop_logo_update/', shop_logo_update, name='shop_logo_update'),
    path('add_product/', add_product, name='add_product'),
    path('product_list/', product_list, name='product_list'),
    path('products/', products, name='products'),
    path('product/<int:pid>/', product, name='product'),
    path('update_product/<int:pid>/', update_product, name='update_product'),
    path('update_product_image/<int:pid>/',update_product_image),    path('product_state_change/<str:state>/', change_product_state, name='product_state_change'),
    path('order_list/',order_list,name='order_list'),
    path('ship_product/<int:order_id>/',ship_product),
    path('urge_comment/<int:order_id>/',urge_comment),
    path('coupons/',coupons,name='coupons'),
    path('coupon_add/<int:pid>/',coupon_add,name='coupon_add'),
    path('coupon_delete/<int:cid>/',coupon_delete),
    path('product_types/',product_types),
    path('ptype_delete/<int:ptid>/',ptype_delete),
    path('ptype_add/',ptype_add),
    path('messages/',message_list),
    path('extrainfo/',extra_info),
    path('extrainfo/<int:type>/',extra_info),
    path('comment_delete/<int:cid>/',comment_delete),
]

shop_system/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include("shop.urls")),
    path('', include("user.urls")),
]

shop/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class User(models.Model):
    username = models.CharField(max_length=32, verbose_name="用户名")
    password = models.CharField(max_length=32, verbose_name="密码")
    nickname = models.CharField(max_length=16, verbose_name="昵称", null=True, blank=True)
    phoneNumber = models.CharField(max_length=16, verbose_name="手机号码", null=True, blank=True)
    email = models.EmailField(verbose_name="邮箱", null=True, blank=True)
    avatar = models.ImageField(upload_to="shop/images", verbose_name="头像", null=True, blank=True)

    address = models.CharField(max_length=32,verbose_name="地址",null=True,blank=True)
    creditCard = models.CharField(max_length=32,verbose_name="银行卡号",null=True,blank=True)

    def __str__(self):
        return self.username

class ShopType(models.Model):
    shopType = models.CharField(max_length=32, verbose_name="店铺类型")
    description = models.TextField(verbose_name="详细信息")

    def __str__(self):
        return self.shopType

class Shop(models.Model):
    shopName = models.CharField(max_length=32, verbose_name="店铺名称")
    address = models.CharField(max_length=32, verbose_name="地址")
    description = models.TextField(verbose_name="描述")
    avatar = models.ImageField(upload_to="shop/images", verbose_name="logo")
    phoneNumber = models.CharField(max_length=32, verbose_name="联系电话")
    sales = models.FloatField(verbose_name="营业额")
    userId = models.IntegerField(verbose_name="店主")
    type = models.ForeignKey(to=ShopType, on_delete=models.CASCADE, verbose_name="店铺类型",null=True)
    def __str__(self):
        return self.shopName

class ProductType(models.Model):
    product_type = models.CharField(max_length=32, verbose_name="商品类型")
    description = models.TextField(verbose_name="详细信息")
    picture = models.ImageField(upload_to="shop/images",verbose_name="首页展示图",null=True)

    def __str__(self):
        return self.product_type

class Product(models.Model):
    name = models.CharField(max_length=32, verbose_name="商品名称")
    price = models.FloatField(verbose_name="商品价格")
    image = models.ImageField(upload_to="shop/images", verbose_name="商品图片")
    stock = models.IntegerField(verbose_name="库存")
    sales = models.IntegerField(verbose_name="销量", default=0)
    description = models.TextField(verbose_name="商品描述")
    createdDate = models.DateField(verbose_name="上架时间")
    product_type = models.ForeignKey(to=ProductType,on_delete=models.CASCADE,verbose_name="商品类型",null=True)
    shopId = models.ForeignKey(to=Shop, on_delete=models.CASCADE, verbose_name="商品店铺", null=True)
    on_sale = models.IntegerField(verbose_name="状态",default=0)
    score = models.IntegerField(verbose_name="评分")
    def __str__(self):
        return self.name

class ProductImage(models.Model):
    address = models.ImageField(upload_to="shop/images", verbose_name="图片地址")
    description = models.TextField(verbose_name="图片描述")
    productId = models.ForeignKey(to=Product,on_delete=models.CASCADE, verbose_name="商品id")

class Comment(models.Model):
    user_id = models.IntegerField(verbose_name="发布用户")
    product = models.ForeignKey(to=Product,on_delete=models.CASCADE,verbose_name="所属产品")
    content = models.TextField(verbose_name="评论内容")
    score = models.IntegerField(verbose_name="评分")
    create_time = models.DateTimeField(verbose_name="发布时间")

    def __str__(self):
        return self.content

class Message(models.Model):
    content = models.TextField(verbose_name="消息内容")
    message_type = models.IntegerField(verbose_name="消息类型")
    # 1- shop-to-user 2- user-to-shop
    message_time = models.DateTimeField(verbose_name="生成时间",default=timezone.now())
    from_id = models.IntegerField(verbose_name="发送者")
    to_id = models.IntegerField(verbose_name="接收人")
    have_read = models.BooleanField(verbose_name="已读",default=False)

    def __str__(self):
        return self.content

class Follow(models.Model):
    follow_time = models.DateTimeField(verbose_name="关注时间")
    user_id = models.IntegerField(verbose_name="关注者")
    shop = models.ForeignKey(to=Shop,on_delete=models.CASCADE,verbose_name="关注店铺")
    def __str__(self):
        return self.shop.shopName

class Coupon(models.Model):
    create_time = models.DateTimeField(default=timezone.now(),verbose_name="创建时间")
    product = models.ForeignKey(to=Product,on_delete=models.CASCADE,verbose_name="所属商品")
    #end_time = models.DateTimeField(default=timezone.now(),verbose_name="截止时间")
    discount = models.FloatField(verbose_name="优惠金额")

    def __str__(self):
        return str(self.product)

shop/views.py
import hashlib
import json
import random

from datetime import timedelta
from django.core import serializers
from django.utils.safestring import mark_safe
from django.views.decorators.csrf import csrf_exempt
from pyecharts.faker import Faker
from pyecharts.globals import ThemeType
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from django.core.paginator import Paginator
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib import messages
from django.utils import timezone
from django.http import JsonResponse,HttpResponse
from django.shortcuts import render, HttpResponseRedirect, redirect
from user.models import Order
from shop.models import User,Shop,ShopType,Product,ProductType,Comment,Coupon,Follow,Message
from user.models import OrderItem,Favorite


from pyecharts import options as opts
from pyecharts.charts import Bar, Pie, Line


# Create your views here.

def setPassword(password):
    md5 = hashlib.md5()
    md5.update(password.encode())
    result = md5.hexdigest()
    return result

def get_random_nickname():
    send = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    mac_str = ''
    for i in range(10):
        mac_str += random.choice(send)
    return "商户" + mac_str

@csrf_exempt
def sign_up(request):
    result = {"status":"error","data":""}
    response = render(request,"shop/sign_up.html",locals())
    if request.is_ajax():
        username = request.POST.get("username")
        password = request.POST.get("password")
        password1 = request.POST.get("confirm_password")
        email = request.POST.get("email")
        if not (username and password and password1 and email):
            result["data"] = "信息不能为空"
            response = JsonResponse({"data":result})
            return response
        user = User.objects.filter(username=username).first()
        print(user)
        if user:
            result["data"] = "用户名已存在"
            response = JsonResponse({"data":result})
            return response
        if password1 != password:
            result["data"] = "两次密码不匹配"
            response = JsonResponse({"data":result})
            return response
        user = User()
        user.username = username
        user.password = setPassword(password)
        user.email = email
        user.nickname = get_random_nickname()
        user.save()
        result["status"] = "success"
        response = JsonResponse({"data":result})
        return response
    return response

@csrf_exempt
def login(request):
    result = {"status":"error","data":"?"}

    response = render(request,"shop/login.html",{'result': json.dumps(result)})
    response.set_cookie("user_login_from","legitimate")
    if request.method == "POST":

        username = request.POST.get("username")
        password = request.POST.get("password")
        print(username,password)
        if username and password:
            user = User.objects.filter(username=username).first()
            if user:
                web_password = setPassword(password)

                cookies = request.COOKIES.get("user_login_from")
                if web_password == user.password:
                    result["status"] = "success"
                    result["data"] = "登录成功"
                    response = JsonResponse({"data":result})

                    shop = Shop.objects.filter(userId=user.id).first()
                    if shop:
                        response.set_cookie("shop_registered",shop.id)
                    else:
                        response.set_cookie("shop_registered","")
                        result["status"] = "no_shop"
                        response = JsonResponse({"data":result})
                    response.set_cookie("shop_username", user.username)
                    response.set_cookie("shop_userId", user.id)
                    return response
                else:
                    result["data"] = "密码错误"
                    response = JsonResponse({"data":result})
                    return response
            else:
                result["data"] = "用户名不存在"
                response = JsonResponse({"data":result})
                return response
        else:
            result["data"] = "用户名和密码不能为空"
            response = JsonResponse({"data":result})
            return response

    return response

def loginValid(fun):
    def inner(request,*args,**kwargs):
        # 获取成功登录后的cookie和session
        c_user = request.COOKIES.get("shop_username")

        # 如果cookie和session都存在并且值都相同
        if c_user:
            # 通过c_user查询数据库
            user = User.objects.filter(username=c_user).first()
            # 如果有这个用户，则返回函数，这里只index
            if user:
                return fun(request,*args,**kwargs)
        # 否则重定向到登录页面
        return HttpResponseRedirect("/shop/login/")
    return inner

@loginValid
def index(request):
    userId = request.COOKIES.get("shop_userId")
    if userId:
        userId = int(userId)
    else:
        userId = -1
    # 通过用户查询店铺是否存在（店铺和用户通过用户的id进行关联）
    shop = Shop.objects.filter(userId=userId).first()
    return render(request,"shop/index_new.html",{"shop":shop})

def exit(request):
    response = HttpResponseRedirect("/shop/login/")
    for key in request.COOKIES:
        response.delete_cookie(key)

    # 跳转到登录
    return response

#register a shop
def shop_register(request):
    type_list = ShopType.objects.all()
    if request.method == "POST":
        post_data = request.POST
        shopName = post_data.get("name")
        address = post_data.get("address")
        description = post_data.get("description")
        phone = post_data.get("phoneNumber")
        user_id = request.COOKIES.get("shop_userId")
        type1 = post_data.get("type")
        logo = request.FILES.get("avatar")

        shop = Shop()
        shop.shopName = shopName
        shop.address = address
        shop.description = description
        shop.phoneNumber = phone
        shop.userId = user_id
        shop.avatar = logo
        st = ShopType.objects.get(shopType=type1)
        shop.type = st
        shop.save()
        response = HttpResponseRedirect("/shop/index/")
        response.set_cookie("shop_registered",shop.id)
        return response

    return render(request,"shop/shop_register.html",locals())

def shop_logo_update(request):
    shopId = request.COOKIES.get("shop_registered")
    shop = Shop.objects.get(id=shopId)
    if request.method == "POST":
        image = request.FILES.get("image")
        if image:
            shop.avatar = image
            messages.add_message(request,messages.SUCCESS,'logo修改成功',extra_tags='success')
        shop.save()

        return HttpResponseRedirect('/shop/index/')
    show_image = shop.avatar
    return render(request,'image_update.html',locals())

#update shop info
@csrf_exempt
def shop_update(request):
    shopId = request.COOKIES.get("shop_registered")
    shop = Shop.objects.get(id=shopId)
    if request.is_ajax():
        post_data = request.POST
        shopName = post_data.get("name")
        address = post_data.get("address")
        description = post_data.get("description")
        phone = post_data.get("phoneNumber")

        shop.shopName = shopName
        shop.address = address
        shop.description = description
        shop.phoneNumber = phone
        shop.save()
        messages.add_message(request,messages.SUCCESS,'信息修改成功',extra_tags='success')
        return JsonResponse({"status":"success"})

    return JsonResponse({"status":"error"})

#add a new product for current shop
@csrf_exempt
def add_product(request):
    if request.is_ajax():
        postdata = request.POST
        name = postdata.get("name")
        price = postdata.get("price")
        description = postdata.get("description")
        stock = postdata.get("stock")
        type = postdata.get('product_type')
        #image = request.FILES.get("image")

        date = timezone.now()
        user_id = int(request.COOKIES.get("shop_userId"))
        shop = Shop.objects.filter(userId=user_id).first()
        product = Product()
        product.name = name
        product.price = price
        product.description = description
        product.stock = stock
        product.createdDate = date
        product.shopId = shop
        product.score = 0
        #if image:
            #product.image = image
        #else :
        product.image = 'shop/images/no_image.png'
        product.product_type = ProductType.objects.get(product_type=type)
        product.save()
        messages.add_message(request,messages.SUCCESS,'商品添加成功',extra_tags='success')
        return JsonResponse({"status":"success"})

    return  JsonResponse({"status":"error"})

#get all products from current shop
@loginValid
def product_list(request):
    pt_list = ProductType.objects.all()
    keywords = request.GET.get("keywords","")
    page_num = request.GET.get("page_num",1)
    shop_registered = int(request.COOKIES.get("shop_registered"))
    shop = Shop.objects.filter(id=shop_registered).first()
    if keywords:
        plist = Product.objects.filter(shopId=shop,name__contains=keywords)
    else:
        plist = Product.objects.filter(shopId=shop)
    paginator = Paginator(plist,10)
    page = paginator.page(int(page_num))
    page_range = paginator.page_range
    return render(request,"shop/product_list1.html",locals())

#get all products
def products(request):
    keywords = request.GET.get("keywords","")
    page_num = request.GET.get("page_num",1)
    if keywords:
        plist = Product.objects.filter(name__contains=keywords)
    else:
        plist = Product.objects.all()
    paginator = Paginator(plist,3)
    page = paginator.page(int(page_num))
    page_range = paginator.page_range
    return render(request,"shop/product_list1.html",locals())

# show product info
@loginValid
def product(request, pid):
    product = Product.objects.filter(id=pid).first()
    comments = Comment.objects.filter(product_id=product.id).order_by('-create_time')

templates/shop/add_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>add_product</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data">
        <div>
            {% csrf_token %}
        </div>
        <div>
            <input type="text" name="name" placeholder="商品名称">
        </div>
        <div>
            <input type="text" name="price" placeholder="商品价格">
        </div>
        <div>
            <input type="text" name="description" placeholder="商品描述">
        </div>
        <div>
            <input type="text" name="stock" placeholder="商品库存">
        </div>
        <div>
            商品图片
            <input type="file" name="image" placeholder="商品图片">
        </div>
        <div>
            <input type="submit" value="添加">
        </div>
    </form>
</body>
</html>

templates/shop/coupons.html
{% load static %}
{% load shop_extras %}
<!doctype html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>优惠券管理</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'user/css/all.css' %}" />
    <link rel="stylesheet" href="{% static 'user/css/order.css' %}" />

    <script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <style>
        body {
            /* background-color: wheat; */
            background-image: url("{% static 'user/images/background/bg2_yellow.jpg' %}");
            background-repeat: no-repeat;
            background-size: 100%;
            background-position: 0 -200px;
        }

        main>.container-fluid,
        main>.container {
            border-radius: 1%;
            border: #fff 1px solid;
            background-color: whitesmoke;
        }

        img {
            width: 100%;
        }

        ul {
            border: 0;
        }

        .nav-pills a {
            border-bottom: 1px solid #ddd;

        }



        table th,
        table td {
            text-align: center;
            vertical-align: middle !important;
        }

        .panel-default>.panel-heading {
            background-color: lightsteelblue;
        }

        .panel-default {
            border-color: #fff;
        }

        .panel-group .panel-heading+.panel-collapse>.panel-body {
            border-top: 1px solid #fff;
        }

        .save {
            padding: 6px 30px;
        }
    </style>
</head>

<body>
    <!-- 导航栏 -->
    {% show_nav_part %}
    <!--主体内容-->
    <main style="margin-top: 55px;">
        <div class="container-fluid">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2" id="sidebar-part">
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="/shop/index/">店铺信息</a></li>
                        <li><a href="/shop/product_list/">商品管理</a></li>
                        <li><a href="/shop/product_types/">商品类别管理</a></li>
                        <li><a href="/shop/order_list/">订单管理</a></li>

                        <li class="active"><a href="/shop/coupons/">优惠券管理</a></li>
                        <li><a href="/shop/messages/">消息管理</a></li>
                        <li><a href="/shop/extrainfo/">销售情况</a></li>
                    </ul>
                </div>

                <div class="col-md-10">
                    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">


                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingOne">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"
                                        aria-expanded="true" aria-controls="collapseOne" style="display: block;">
                                        全部优惠券
                                    </a>
                                </h4>
                            </div>


                            <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel"
                                aria-labelledby="headingOne">
                                <div class="panel-body">
                                    <div class="col-md-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th></th>
                                                    <th>商品名称</th>
                                                    <th>优惠金额</th>
                                                    <th>操作</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for coupon in coupon_list %}
                                                    <tr data-id="{{ coupon.id }}">
                                                        <td width="8%">
                                                            <div class="img-frame"><img src="/static/{{ coupon.product.image }}"
                                                                    alt=""></div>
                                                        </td>
                                                        <td width="35">{{ coupon.product.name }}</td>
                                                        <td width="35%">￥<span>{{ coupon.discount }}</span></td>
                                                        <td width="22%"><button type="button" class="btn btn-danger"
                                                                data-toggle="modal" data-target="#confirm-Modal"
                                                                onclick="deleteCoupon(this)">删除</button></td>
                                                    </tr>
                                                {% endfor %}


                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

    {% show_footer %}
</body>
<script type="text/javascript">
    $("#nav_part").load("nav-part.html");
    $("#footer-part").load("../footer-part.html");


    //删除优惠券
    function deleteCoupon(button) {
        let theButton = $(button);
        let couponId = theButton.parent().parent().attr("data-id");

        console.log(couponId);
        window.open("/shop/coupon_delete/" + couponId+'/', "_self");
    }
</script>

</html>

templates/shop/extra_info.html
{% load static %}
{% load shop_extras %}
<!doctype html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>销售情况</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'user/css/all.css' %}" />
    <link rel="stylesheet" href="{% static 'user/css/order.css' %}" />


    <script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <style>
        body {
            /* background-color: wheat; */
            background-image: url("{% static 'user/images/background/bg2_yellow.jpg' %}");
            background-repeat: no-repeat;
            background-size: 100%;
            background-position: 0 -200px;
        }

        main>.container-fluid,
        main>.container {
            border-radius: 1%;
            border: #fff 1px solid;
            background-color: whitesmoke;
        }

        img {
            width: 100%;
        }

        ul {
            border: 0;
        }

        .nav-pills a {
            border-bottom: 1px solid #ddd;
        }

        .panel-default>.panel-heading {
            background-color: lightsteelblue;
        }

        .panel-default {
            border-color: #fff;
        }

        .panel-group .panel-heading+.panel-collapse>.panel-body {
            border-top: 1px solid #fff;
        }

        .save {
            padding: 6px 30px;
        }
    </style>
</head>

<body>
    <!-- 导航栏 -->
    {% show_nav_part %}
    <!--主体内容-->
    <main style="margin-top: 55px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2" id="sidebar-part">
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="/shop/index/">店铺信息</a></li>
                        <li><a href="/shop/product_list/">商品管理</a></li>
                        <li><a href="/shop/product_types/">商品类别管理</a></li>
                        <li><a href="/shop/order_list/">订单管理</a></li>
                        <li><a href="/shop/coupons/">优惠券管理</a></li>
                        <li><a href="/shop/messages/">消息管理</a></li>
                        <li class="active"><a href="/shop/extrainfo/">销售情况</a></li>
                    </ul>
                </div>
                <div class="col-md-10">
                    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingOne">
                                <h4 class="panel-title">
                                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne"
                                        aria-expanded="true" aria-controls="collapseOne">
                                        销售情况
                                    </a>
                                </h4>
                            </div>


                            <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel"
                                aria-labelledby="headingOne">
                                <div class="col-md-12" style="margin-top: 100px; margin-bottom: 100px;">
                                    <div class="col-md-3 ">
                                        <button class="btn btn-lg btn-info" onclick="window.open('/shop/extrainfo/1/','_blank')" style="width: 100%;">店铺销量展示</button>
                                    </div>

                                    <div class="col-md-3 col-md-offset-1">
                                        <button class="btn btn-lg btn-info" onclick="window.open('/shop/extrainfo/2/','_blank')" style="width: 100%;">店铺销售额汇总</button>
                                    </div>

                                    <div class="col-md-3 col-md-offset-1">
                                        <button class="btn btn-lg btn-info" onclick="window.open('/shop/extrainfo/3/','_blank')" style="width: 100%;">店铺信息变化</button>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </main>

    {% show_footer %}
</body>
<script type="text/javascript">
</script>

</html>

templates/shop/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shop</title>
</head>
<body>
<h1>Index Page</h1>
{% if request.COOKIES.shop_username %}
    <strong>{{ request.COOKIES.shop_username }}</strong>
    <a href="{% url 'shop:logout' %}">退出登录</a>
    {% if request.COOKIES.shop_registered %}
        <div>已经注册店铺</div>
        <div>店名 ： {{ shop.shopName }}</div>
        <div>店址 ： {{ shop.address }}</div>
        <div>描述 ： {{ shop.description }}</div>
        <div>
            <img style="width: 200px;height: 200px;" src="/static/{{ shop.avatar }}">
        </div>

        <a href="{% url 'shop:shop_update' %}"><span>更改店铺信息</span></a>
        <br>
        <a href="{% url 'shop:add_product' %}"><span>增加商品</span></a>
        <br>
        <a href="{% url 'shop:product_list' %}"><span>查看本店商品</span></a>
        <a href="{% url 'shop:products' %}"><span>查看所有商品</span></a>
    {% else %}
        <div>还未注册店铺</div>
        <a href="{% url 'shop:shop_register' %}"><span>注册店铺</span></a>
    {% endif %}
{% else %}
    <a href="{% url 'shop:sign_up' %}">立即注册</a> |
    <a href="{% url 'shop:login' %}">立即登录</a> |

{% endif %}

</body>
</html>

templates/shop/product_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>product_list</title>
</head>
<body>
    <form>
        <div>
            <input type="text" name = "keywords" value="{{ keywords }}" placeholder="阿哲">
            <input type="submit" value="搜">
        </div>
    </form>
    <table>
        <thead>
            <tr>
                <th>商品名称</th>
                <th>商品价格</th>
                <th>商品库存</th>
                <th>描述</th>
                <th>上架日期</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for p in page %}
            <tr>
                <td>
                    <a href="/shop/product/{{ p.id }}">{{ p.name }}</a></td>
                <td>{{ p.price }}</td>
                <td>{{ p.stock }}</td>
                <td>{{ p.description }}</td>
                <td>{{ p.createdDate }}</td>
                <td>
                     {% if p.on_sale == 1 %}
                         <a href="/shop/product_state_change/down/?id={{ p.id }}">下架</a>
                     {% else %}
                         <a href="/shop/product_state_change/up/?id={{ p.id }}">上架</a>
                     {% endif %}
                    <a href="/shop/product_state_change/delete/?id={{ p.id }}">销毁</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div>
        <ul>
            {% for p in page_range %}
            <li>
                <a href="?keywords={{ keywords }}&page_num={{ p }}">{{ p }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div><a href="{% url 'shop:index' %}">返回</a></div>
</body>
</html>