shop/urls.py
from django.urls import path
from shop.views import *

app_name = 'shop'
urlpatterns = [
    path('',index),
    path('sign_up/',sign_up, name='sign_up'),
    path('login/',login, name='login'),
    path('logout/',exit, name='logout'),
    path('index/',index, name='index'),
    path('shop_register/', shop_register, name='shop_register'),
    path('shop_update/', shop_update, name='shop_update'),
    path('shop_logo_update/', shop_logo_update, name='shop_logo_update'),
    path('add_product/', add_product, name='add_product'),
    path('product_list/', product_list, name='product_list'),
    path('products/', products, name='products'),
    path('product/<int:pid>/', product, name='product'),
    path('update_product/<int:pid>/', update_product, name='update_product'),
    path('update_product_image/<int:pid>/',update_product_image),    path('product_state_change/<str:state>/', change_product_state, name='product_state_change'),
    path('order_list/',order_list,name='order_list'),
    path('ship_product/<int:order_id>/',ship_product),
    path('urge_comment/<int:order_id>/',urge_comment),
    path('coupons/',coupons,name='coupons'),
    path('coupon_add/<int:pid>/',coupon_add,name='coupon_add'),
    path('coupon_delete/<int:cid>/',coupon_delete),
    path('product_types/',product_types),
    path('ptype_delete/<int:ptid>/',ptype_delete),
    path('ptype_add/',ptype_add),
    path('messages/',message_list),
    path('extrainfo/',extra_info),
    path('extrainfo/<int:type>/',extra_info),
    path('comment_delete/<int:cid>/',comment_delete),
]

shop_system/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include("shop.urls")),
    path('', include("user.urls")),
]

user/urls.py
from django.urls import path
from user.views import *

app_name = 'user'
urlpatterns = [
    path('',index),
    path('index/',index,name='index'),
    path('sign_up/',register,name='register'),
    path('login/',login,name='login'),
    path('logout/',exit,name='logout'),
    path('user_info/',user_info,name='user_info'),
    path('user_address/',user_address,name='user_address'),
    path('user_coupon/',user_coupon,name='user_coupon'),
    path('user_info_update/',user_info_update,name='user_info_update'),
    path('user_avatar_update/',user_avatar_update,name='user_avatar_update'),
    path('user_password_update/',user_password_update,name='user_password_update'),
    path('add_address/',add_address,name='add_address'),
    path('address_update/<int:add_id>',address_update,name='address_update'),
    path('address_delete/<int:add_id>',address_delete,name='address_delete'),
    path('product_list/',product_list,name='product_list'),
    path('product_list/<int:type_id>/',product_list,name='product_list'),
    path('product/<int:pid>/',product,name='product'),
    path('cart/',cart,name='cart'),
    path('process/',process_cart_info,name='process_cart_info'),
    path('footprint/',footprint,name='footprint'),
    path('favorite/',favorite,name='favorite'),
    path('order/<int:order_id>/',order,name='order'),
    path('order_list/',order_list,name='order_list'),
    path('add_to_cart/<int:pid>/',add_to_cart,name='add_to_cart'),
    path('add_to_favorite/<int:pid>/',add_to_favorite,name='add_to_favorite'),
    path('delete_cart_item/<int:pid>/',delete_cart_item,name='delete_cart_item'),
    path('cancel_favorite/<int:pid>/',cancel_favorite,name='cancel_favorite'),
    path('checkout/',gen_order,name='checkout'),
    path('place_order_success/',place_order_success,name='place_order_success'),
    path('comment/<int:pid>/',comment,name='comment'),
    path('messages/',message_list,name="messages"),
    path('follow/<int:sid>/',follow_shop,name="follow_shop"),
    path('unfollow/<int:sid>/',cancel_follow,name="unfollow_shop"),
    path('shopinfo/<int:sid>/',shop_info,name="shop_info"),
    path('receive_product/<int:order_id>/',receive_product),
    path('finish_order/<int:order_id>/',finish_order),
]

user/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    username = models.CharField(max_length=32, verbose_name="用户名")
    nickname = models.CharField(max_length=32, verbose_name="昵称")
    password = models.CharField(max_length=32, verbose_name="密码")
    email = models.EmailField(verbose_name="邮箱")
    avatar = models.ImageField(upload_to="user/images", verbose_name="头像",default="user\images\default_avatar.png",null=True,blank=True)
    phone = models.CharField(max_length=32, verbose_name="联系电话",null=True,blank=True)
    contact_address = models.TextField(verbose_name="联系地址",null=True,blank=True)

    def __str__(self):
        return self.username

class Address(models.Model):
    address = models.TextField(verbose_name="收货地址")
    receiver = models.CharField(max_length=32, verbose_name="收货人")
    receive_phone = models.CharField(max_length=32, verbose_name="联系电话")
    postNumber = models.CharField(max_length=32, verbose_name="邮编")
    user_id = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name="用户ID")
    def __str__(self):
        return self.address

class Order(models.Model):
    order_id = models.CharField(max_length=64, verbose_name="订单编号")
    order_user = models.ForeignKey(to=User,on_delete=models.CASCADE,verbose_name="订单用户")
    order_shop = models.IntegerField(verbose_name="店铺id")
    order_address = models.ForeignKey(to=Address,on_delete=models.CASCADE,verbose_name="收货地址")
    order_status = models.IntegerField(verbose_name="订单状态")
    # 0-未发货 1-已发货 2-已收货 3-已评价 4-失败 5-全部
    order_price = models.FloatField(verbose_name="订单总额")
    order_date = models.DateTimeField(verbose_name="下单时间")
    def __str__(self):
        return self.order_id

class OrderItem(models.Model):
    order = models.ForeignKey(to=Order,on_delete=models.CASCADE,verbose_name="所属订单")
    product_id = models.IntegerField(verbose_name="商品id")
    product_name = models.CharField(max_length=32,verbose_name="商品名称")
    product_price = models.FloatField(verbose_name="商品价格")
    product_number = models.IntegerField(verbose_name="商品数量")
    total_price = models.FloatField(verbose_name="商品总价")
    shop_id = models.IntegerField(verbose_name="店铺id")
    def __str__(self):
        return str(self.order)

class Cart(models.Model):
    cart_user = models.ForeignKey(to=User,on_delete=models.CASCADE,verbose_name="订单用户")
    def __str__(self):
        return self.cart_user

class CartItem(models.Model):
    cart_user = models.ForeignKey(to=User,on_delete=models.CASCADE,verbose_name="所属用户")
    product_id = models.IntegerField(verbose_name="商品id")
    product_name = models.CharField(max_length=32,verbose_name="商品名称")
    product_price = models.FloatField(verbose_name="商品价格")
    product_number = models.IntegerField(verbose_name="商品数量")
    total_price = models.FloatField(verbose_name="商品总价")
    shop_id = models.IntegerField(verbose_name="店铺id")
    def __str__(self):
        return self.cart_user.username + ' ' + self.product_name + ' ' + str(self.product_number)

class Favorite(models.Model):
    user_id = models.IntegerField(verbose_name='所属用户')
    product_id = models.IntegerField(verbose_name='所属商品')
    create_time = models.DateTimeField(verbose_name='添加时间')

class FootPrint(models.Model):
    user_id = models.IntegerField(verbose_name='所属用户')
    product_id = models.IntegerField(verbose_name='所属商品')
    create_time = models.DateTimeField(verbose_name='访问时间')

user/views.py
import hashlib
import json
import random

from django.core.paginator import Paginator
from django.shortcuts import render, redirect,get_object_or_404
from django.template import RequestContext
from django.core import serializers
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, HttpResponseRedirect, redirect
from user.models import User,Address,OrderItem,Order,CartItem,Favorite,FootPrint
from shop.models import ProductType,Product,Shop,Comment,Follow,Message,Coupon

# Create your views here.
def setPassword(password):
    md5 = hashlib.md5()
    md5.update(password.encode())
    result = md5.hexdigest()
    return result

def get_random_nickname():
    send = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    mac_str = ''
    for i in range(10):
        mac_str += random.choice(send)
    return "用户" + mac_str

@csrf_exempt
def register(request):
    result = {"status":"error","data":""}
    response = render(request,"user/sign_up.html",locals())
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        password1 = request.POST.get("password_confirm")
        email = request.POST.get("email")
        if not (username and password and password1 and email):
            result["data"] = "信息不能为空"
            response = JsonResponse({"data":result})
            return response
        user = User.objects.filter(username=username).first()

        if user:
            result["data"] = "用户名已存在"
            response = JsonResponse({"data":result})
            return response
        if password1 != password:
            result["data"] = "两次密码不匹配"
            response = JsonResponse({"data":result})
            return response
        user = User()
        user.username = username
        user.password = setPassword(password)
        user.email = email
        user.nickname = get_random_nickname()
        user.save()
        result["status"] = "success"
        response = JsonResponse({"data":result})
        return response
    return response

@csrf_exempt
def login(request):
    result = {"status":"error","data":"?"}

    response = render(request,"user/login.html",{'result': json.dumps(result)})
    response.set_cookie("user_login_from","legitimate")
    if request.method == "POST":

        username = request.POST.get("username")
        password = request.POST.get("password")
        print(username,password)
        if username and password:
            user = User.objects.filter(username=username).first()
            if user:
                web_password = setPassword(password)

                cookies = request.COOKIES.get("user_login_from")
                if web_password == user.password:
                    result["status"] = "success"
                    result["data"] = "登录成功"
                    response = JsonResponse({"data":result})
                    response.set_cookie("user_username", user.username)
                    response.set_cookie("user_userId", user.id)

                    return response
                else:
                    result["data"] = "密码错误"
                    response = JsonResponse({"data":result})
                    return response
            else:
                result["data"] = "用户名不存在"
                response = JsonResponse({"data":result})
                return response
        else:
            result["data"] = "用户名和密码不能为空"
            response = JsonResponse({"data":result})
            return response

    return response


def loginValid(fun):
    def inner(request,*args,**kwargs):
        c_user = request.COOKIES.get("user_username")
        if c_user:
            return fun(request, *args, **kwargs)
        else:
            return HttpResponseRedirect("/login/")
    return inner

#@loginValid
def index(request):
    product_type_list = ProductType.objects.all()
    best_sales = Product.objects.filter(on_sale=1).order_by('-sales')[:8]
    product_list1 = Product.objects.filter(on_sale=1).order_by('createdDate')[:6]
    product_list2 = Product.objects.filter(on_sale=1).order_by('price')[:6]
    return render(request,"user/index.html",locals())

def exit(request):
    response = HttpResponseRedirect("/login/")
    for key in request.COOKIES:
        response.delete_cookie(key)
    #del request.session["user_username"]
    # 跳转到登录
    return response

@loginValid
def user_info(request):
    user_id = request.COOKIES.get("user_userId")
    user = User.objects.filter(id=user_id).first()
    address_list = Address.objects.filter(user_id=user)
    order_list = Order.objects.filter(order_user=user)
    return render(request,"user/user_info.html",locals())

def user_update(request):
    user_id = request.COOKIES.get("user_userId")
    user = User.objects.filter(id=user_id).first()
    if request.method == "POST":
        nickname = request.POST.get("nickname")
        email = request.POST.get("email")
        phone = request.POST.get("phone")
        address = request.POST.get("contact_address")
        image = request.FILES.get("avatar")

        user.nickname = nickname
        user.email = email
        user.phone = phone
        user.contact_address = address
        if image:
            user.avatar = image
        user.save()
        return HttpResponseRedirect("/user_info/")
    return render(request, "user/user_update.html",locals())

@csrf_exempt
def user_avatar_update(request):
    user_id = request.COOKIES.get("user_userId")
    user = User.objects.filter(id=user_id).first()
    if request.method == "POST":
        image = request.FILES.get("image")
        print(image)
        if image:
            user.avatar = image
            messages.add_message(request,messages.SUCCESS,'头像修改成功',extra_tags='success')
        user.save()

        return HttpResponseRedirect('/user_info/')
    show_image = user.avatar
    return render(request,'image_update.html',locals())

@csrf_exempt
def user_info_update(request):
    user_id = request.COOKIES.get("user_userId")
    user = User.objects.filter(id=user_id).first()
    if request.method == "POST":
        nickname = request.POST.get("nickname")
        email = request.POST.get("email")
        phone = request.POST.get("phone")

        user.nickname = nickname
        user.email = email
        user.phone = phone
        user.save()
        messages.add_message(request,messages.SUCCESS,'个人信息修改成功',extra_tags='success')

        return  JsonResponse({"status":"success"})
    return  JsonResponse({"status":"error"})


@csrf_exempt
def user_password_update(request):
    user_id = request.COOKIES.get("user_userId")
    user = User.objects.filter(id=user_id).first()
    data = ""
    if request.method == "POST":
        current_password = request.POST.get("current_password")
        current_password = setPassword(current_password)
        new_password = request.POST.get("new_password")
        new_password_confirm = request.POST.get("new_password_confirm")

        if not (current_password and new_password and new_password_confirm) :
            data = '信息不能为空'
            return  JsonResponse({"status":"error",'data':data})
        if current_password != user.password:
            data = '当前密码输入错误'
            return  JsonResponse({"status":"error",'data':data})
        if new_password != new_password_confirm:
            data = '确认密码输入错误'
            return  JsonResponse({"status":"error",'data':data})
        user.password = setPassword(new_password)
        user.save()
        messages.add_message(request,messages.SUCCESS,'密码修改成功',extra_tags='success')

        return  JsonResponse({"status":"success",'data':data})
    return  JsonResponse({"status":"error",'data':data})


def user_coupon(request):
    user_id = request.COOKIES.get("user_userId")
    follows = Follow.objects.filter(user_id=user_id)
    coupons = []
    product_names = {}
    shop_names = {}
    for follow in follows:
        coupon = Coupon.objects.filter(product__shopId_id=follow.shop.id)
        for c in coupon:
            product_names[c.product.id] = c.product.name
            shop_names[c.product_id] = c.product.shopId.shopName
            coupons.append(c)
    cps = serializers.serialize('json',coupons)
    pns = json.dumps(product_names)
    sns = json.dumps(shop_names)
    return render(request, "user/user_coupon.html",{
        'coupons':mark_safe(cps),
        'product_names':mark_safe(pns),
        'shop_names':mark_safe(sns)
    })

def user_address(request):
    user_id = request.COOKIES.get("user_userId")
    user = User.objects.filter(id=user_id).first()
    address_list = Address.objects.filter(user_id=user)
    adds = serializers.serialize('json',address_list)
    return render(request,"user/user_address.html",{
        'address_list' : mark_safe(adds)
    })

@csrf_exempt
def add_address(request):
    user_id = request.COOKIES.get("user_userId")
    user = User.objects.filter(id=user_id).first()
    '''
    address = models.TextField(verbose_name="收货地址")
    receiver = models.CharField(max_length=32, verbose_name="收货人")
    receive_phone = models.CharField(max_length=32, verbose_name="联系电话")
    postNumber = models.CharField(max_length=32, verbose_name="邮编")
    user_id = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name="用户ID")
    '''
    if request.is_ajax():
        address = request.POST.get("address")
        receiver = request.POST.get('receiver')
        receiver_phone = request.POST.get('phone')
        #post_num = request.POST.get('post_num')

        add = Address()
        add.address = address
        add.receiver = receiver
        add.receive_phone = receiver_phone
        add.postNumber = "100000"
        add.user_id = user
        add.save()

templates/user/finish_order.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>结算完成</title>
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="../css/all.css" />
    <link rel="stylesheet" href="../css/finish_order.css">
    <script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col-sm-offset-3 col-sm-6">
                <div class="tick">
                    <div class="tickimg"></div>
                    <p>购买成功</p>
                </div>
                <ul style="margin-top: 10px" class="list-group">
                    <li class="list-group-item">
                        <p class="mark">
                            <span class="des-label">订单号：</span>
                            <span>订单号订单号订单号订单号订单号订单号</span>
                        </p>
                        <p>
                            <span class="des-label">商品名称：</span>
                            <span>商品名称商品名称商品名称商品名称商品名称</span>
                        </p>
                        <p>
                            <span class="des-label">商品名称：</span>
                            <span>商品名称商品名称商品名称商品名称商品名称</span>
                        </p>
                    </li>
                </ul>
                <button type="button" class="btn btn-default col-sm-offset-1 col-sm-4"
                    onclick="window.location.href='cart.html'">查看订单</button>
                <button type="button" class="btn btn-success col-sm-offset-1 col-sm-4"
                    onclick="window.location.href='index.html'">继续购物</button>
            </div>
        </div>
    </div>

    <!-- 页脚 -->
    <footer>
        <div class="links">
            <a target="_blank" href="//about.jd.com/">
                关于我们
            </a>
            |
            <a target="_blank" href="//www.jd.com/contact/">
                联系我们
            </a>
        </div>
        <div class="copyright">
            Copyright&nbsp;&copy;&nbsp;2020&nbsp;&nbsp;ytshit&nbsp;版权所有
        </div>
    </footer>

</body>


</html>

templates/user/footprint.html
{% load static %}
{% load user_extras %}
<!DOCTYPE html>
<html>
<meta charset="utf-8" />
<title>收藏夹</title>

<!-- Bootstrap -->
<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css">

<link rel="stylesheet" href="{% static 'user/css/all.css' %}" />
<link rel="stylesheet" href="{% static 'user/css/index.css' %}" />

<script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
<script src="http://cdn.bootcss.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<style>
    button {
        border-radius: 0 !important;
    }



    .imgFrame {
        position: relative;
        width: 100%;
        height: 0;
        padding-top: 100%;
        /* 宽高比例为1：1 */
    }

    .imgFrame img {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        border: 1px wheat solid;
    }

</style>

<style>

</style>

</head>

<body>
    <!-- 导航栏 -->
    {% show_nav_part %}

    <!-- 主体部分 -->

    <main>
        <div class="container-fluid">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="container">
            <div class="row" style="margin-top: 45px">
                <div class="row row-goods">
                    <div class="col-md-12 title">
                        <div class="col-md-5 ">
                            <div class="k-border">
                                <div class="border bor-l">
                                    <div class="border bor-r">
                                        <div class="bor-m"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2 ">浏览历史</div>
                        <div class="col-md-5 ">
                            <div class="k-border">
                                <div class="border bor-l">
                                    <div class="border bor-r">
                                        <div class="bor-m"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% for foot in footprints %}


                        <div class="col-md-2" style="margin-top: 20px;">
                            <div class="imgFrame">
                                <a href="{% url 'user:product' foot.product_id %}"><img src="/static/{{ foot.image }}" alt=""></a>
                            </div>
                            {{ foot.create_time }}
                        </div>

                    {% endfor %}



                </div>
            </div>
        </div>
    </main>


    <!-- 页脚 -->
    {% show_footer %}



</body>

</html>

templates/user/user_coupon.html
{% load static %}
{% load user_extras %}

<!doctype html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>我的优惠券</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'user/css/all.css' %}" />

    <script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <style>
        body {
            /* background-color: wheat; */
            background-image: url("{% static 'user/images/background/bg2.jpg' %}");
            background-repeat: no-repeat;
            background-size: 100%;
            background-position: 0 -30px;

        }

        main>.container {
            background: whitesmoke;
        }

        img {
            width: 100%;
        }

        ul {
            border: 0;
        }

        #address-table tr {
            height: 30px;
        }

        .nav-pills a {
            border-bottom: 1px solid #ddd;

        }

        .panel-default>.panel-heading {
            background-color: lightblue;
        }

        .panel-default {
            border-color: #fff;
        }

        .panel-group .panel-heading+.panel-collapse>.panel-body {
            border-top: 1px solid #fff;
        }

        .save {
            padding: 6px 30px;
        }
    </style>
</head>

<body>
    <!-- 导航栏 -->
    {% show_nav_part %}

    <!--主体内容-->
    <main style="margin-top: 60px;">
        <div class="container-fluid">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="{% url 'user:user_info' %}">我的信息</a></li>
                        <li><a href="{% url 'user:user_address' %}">我的地址</a></li>
                        <li><a href="{% url 'user:order_list'%}">我的订单</a></li>
                        <li class="active"><a href="{% url 'user:user_coupon' %}">我的优惠券</a></li>
                    </ul>
                </div>
                <div class="col-md-9">
                    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingOne">
                                <h4 class="panel-title">
                                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne"
                                        aria-expanded="true" aria-controls="collapseOne">
                                        我的优惠券
                                    </a>
                                </h4>
                            </div>


                            <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel"
                                aria-labelledby="headingOne">
                                <div class="panel-body">
                                    <div class="col-md-12">
                                        <table class="table" style="border-bottom: 1px solid #ddd;" id="address-table">
                                            <thead>
                                                <tr style="text-align: center !important;">
                                                    <th style="width: 10%;">图片</th>
                                                    <th style="width: 30%;">店铺</th>
                                                    <th style="width: 35%;">商品名</th>
                                                    <th>金额</th>
                                                    <th>数量</th>
                                                </tr>
                                            </thead>
                                            <tbody style="height: 60px; overflow-y: auto; " style="text-align: center;">
                                                <tr>
                                                    <td>
                                                        <img src="{% static 'user/images/coupon.jpg' %}" alt="">
                                                    </td>
                                                    <td>
                                                        店铺名称店铺名称
                                                    </td>
                                                    <td>
                                                        商品名商品名
                                                    </td>
                                                    <td>
                                                        ￥5
                                                    </td>
                                                    <td>
                                                        1
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>


                        </div>

                    </div>
                </div>
            </div>
        </div>

    </main>

    <!-- 页脚 -->
    {% show_footer %}

    <!-- <button onclick="loadCouponsInfo()">生成html</button> -->
</body>

<script type="text/javascript">

    var coupons = {{ coupons }};
    var product_names = {{ product_names }};
    var shop_names = {{ shop_names }};
    console.log(coupons);
    console.log(product_names);
    console.log(shop_names);

    loadCouponsInfo();

    var couponList = [{
        id: 1234564876,
        shopName: "店铺名-驱蚊器群",
        goodName: "商品名商品名",
        discount: 5,
        count: 1
    },
    {
        id: 1234564876,
        shopName: "店铺名-驱蚊器群",
        goodName: "商品名商品名",
        discount: 5,
        count: 1
    },
    {
        id: 1234564876,
        shopName: "店铺名-驱蚊器群",
        goodName: "商品名商品名",
        discount: 5,
        count: 2
    },
    {
        id: 1234564876,
        shopName: "店铺名-驱蚊器群",
        goodName: "商品名商品名",
        discount: 5,
        count: 13
    },
    ];
    function loadCouponsInfo() {

        let tbody = $("table tbody");
        tbody.html("")
        $.each(coupons, function (i, item) {
            let tableRow = document.createElement("tr");
            tbody.append(tableRow);

            let imageTd = document.createElement("td");
            imageTd.innerHTML = "<img src=\"{% static 'user/images/coupon.jpg' %}\">";
            tableRow.append(imageTd);

            let shopNameTd = document.createElement("td");
            shopNameTd.innerHTML = shop_names[item.fields.product];
            tableRow.append(shopNameTd);

            let goodNameTd = document.createElement("td");
            goodNameTd.innerHTML = product_names[item.fields.product];
            tableRow.append(goodNameTd);

            let discountTd = document.createElement("td");
            discountTd.innerHTML = "￥" + item.fields.discount;
            tableRow.append(discountTd);

            let countTd = document.createElement("td");
            countTd.innerHTML = "1";
            tableRow.append(countTd);
        });
    }


</script>

</html>